#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioFernandaHackLib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FernandaHackenhaar")]
	public partial class ConsultorioFernandaHackDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPaciente(Paciente instance);
    partial void UpdatePaciente(Paciente instance);
    partial void DeletePaciente(Paciente instance);
    partial void InsertColaborador(Colaborador instance);
    partial void UpdateColaborador(Colaborador instance);
    partial void DeleteColaborador(Colaborador instance);
    partial void InsertHistSessaoPgto(HistSessaoPgto instance);
    partial void UpdateHistSessaoPgto(HistSessaoPgto instance);
    partial void DeleteHistSessaoPgto(HistSessaoPgto instance);
    partial void InsertSessao(Sessao instance);
    partial void UpdateSessao(Sessao instance);
    partial void DeleteSessao(Sessao instance);
    partial void InsertEvolucao(Evolucao instance);
    partial void UpdateEvolucao(Evolucao instance);
    partial void DeleteEvolucao(Evolucao instance);
    partial void InsertAvaliacao(Avaliacao instance);
    partial void UpdateAvaliacao(Avaliacao instance);
    partial void DeleteAvaliacao(Avaliacao instance);
    #endregion
		
		public ConsultorioFernandaHackDataContext() : 
				base(global::ConsultorioFernandaHackLib.Properties.Settings.Default.FernandaHackenhaarConnectionStringProd, mappingSource)
		{
			OnCreated();
		}
		
		public ConsultorioFernandaHackDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConsultorioFernandaHackDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConsultorioFernandaHackDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConsultorioFernandaHackDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Paciente> Pacientes
		{
			get
			{
				return this.GetTable<Paciente>();
			}
		}
		
		public System.Data.Linq.Table<Colaborador> Colaboradors
		{
			get
			{
				return this.GetTable<Colaborador>();
			}
		}
		
		public System.Data.Linq.Table<HistSessaoPgto> HistSessaoPgtos
		{
			get
			{
				return this.GetTable<HistSessaoPgto>();
			}
		}
		
		public System.Data.Linq.Table<Sessao> Sessaos
		{
			get
			{
				return this.GetTable<Sessao>();
			}
		}
		
		public System.Data.Linq.Table<Evolucao> Evolucaos
		{
			get
			{
				return this.GetTable<Evolucao>();
			}
		}
		
		public System.Data.Linq.Table<Avaliacao> Avaliacaos
		{
			get
			{
				return this.GetTable<Avaliacao>();
			}
		}
		
		public System.Data.Linq.Table<vwSessaoHistPgto> vwSessaoHistPgtos
		{
			get
			{
				return this.GetTable<vwSessaoHistPgto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Paciente")]
	public partial class Paciente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPaciente;
		
		private string _Nome;
		
		private string _Telefone;
		
		private string _Telefone2;
		
		private string _RG;
		
		private string _CPF;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _DtNascimento;
		
		private System.Nullable<char> _Sexo;
		
		private System.Nullable<System.DateTime> _ClienteDesde;
		
		private string _Obs;
		
		private EntitySet<Sessao> _Sessaos;
		
		private EntitySet<Evolucao> _Evolucaos;
		
		private EntitySet<Avaliacao> _Avaliacaos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPacienteChanging(int value);
    partial void OnIDPacienteChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnTelefone2Changing(string value);
    partial void OnTelefone2Changed();
    partial void OnRGChanging(string value);
    partial void OnRGChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDtNascimentoChanging(System.Nullable<System.DateTime> value);
    partial void OnDtNascimentoChanged();
    partial void OnSexoChanging(System.Nullable<char> value);
    partial void OnSexoChanged();
    partial void OnClienteDesdeChanging(System.Nullable<System.DateTime> value);
    partial void OnClienteDesdeChanged();
    partial void OnObsChanging(string value);
    partial void OnObsChanged();
    #endregion
		
		public Paciente()
		{
			this._Sessaos = new EntitySet<Sessao>(new Action<Sessao>(this.attach_Sessaos), new Action<Sessao>(this.detach_Sessaos));
			this._Evolucaos = new EntitySet<Evolucao>(new Action<Evolucao>(this.attach_Evolucaos), new Action<Evolucao>(this.detach_Evolucaos));
			this._Avaliacaos = new EntitySet<Avaliacao>(new Action<Avaliacao>(this.attach_Avaliacaos), new Action<Avaliacao>(this.detach_Avaliacaos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPaciente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDPaciente
		{
			get
			{
				return this._IDPaciente;
			}
			set
			{
				if ((this._IDPaciente != value))
				{
					this.OnIDPacienteChanging(value);
					this.SendPropertyChanging();
					this._IDPaciente = value;
					this.SendPropertyChanged("IDPaciente");
					this.OnIDPacienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone2", DbType="Char(15)")]
		public string Telefone2
		{
			get
			{
				return this._Telefone2;
			}
			set
			{
				if ((this._Telefone2 != value))
				{
					this.OnTelefone2Changing(value);
					this.SendPropertyChanging();
					this._Telefone2 = value;
					this.SendPropertyChanged("Telefone2");
					this.OnTelefone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string RG
		{
			get
			{
				return this._RG;
			}
			set
			{
				if ((this._RG != value))
				{
					this.OnRGChanging(value);
					this.SendPropertyChanging();
					this._RG = value;
					this.SendPropertyChanged("RG");
					this.OnRGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DtNascimento", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DtNascimento
		{
			get
			{
				return this._DtNascimento;
			}
			set
			{
				if ((this._DtNascimento != value))
				{
					this.OnDtNascimentoChanging(value);
					this.SendPropertyChanging();
					this._DtNascimento = value;
					this.SendPropertyChanged("DtNascimento");
					this.OnDtNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="Char(1)")]
		public System.Nullable<char> Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClienteDesde", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ClienteDesde
		{
			get
			{
				return this._ClienteDesde;
			}
			set
			{
				if ((this._ClienteDesde != value))
				{
					this.OnClienteDesdeChanging(value);
					this.SendPropertyChanging();
					this._ClienteDesde = value;
					this.SendPropertyChanged("ClienteDesde");
					this.OnClienteDesdeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Obs", DbType="VarChar(400)")]
		public string Obs
		{
			get
			{
				return this._Obs;
			}
			set
			{
				if ((this._Obs != value))
				{
					this.OnObsChanging(value);
					this.SendPropertyChanging();
					this._Obs = value;
					this.SendPropertyChanged("Obs");
					this.OnObsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paciente_Sessao", Storage="_Sessaos", ThisKey="IDPaciente", OtherKey="IDPaciente")]
		public EntitySet<Sessao> Sessaos
		{
			get
			{
				return this._Sessaos;
			}
			set
			{
				this._Sessaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paciente_Evolucao", Storage="_Evolucaos", ThisKey="IDPaciente", OtherKey="IDPaciente")]
		public EntitySet<Evolucao> Evolucaos
		{
			get
			{
				return this._Evolucaos;
			}
			set
			{
				this._Evolucaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paciente_Avaliacao", Storage="_Avaliacaos", ThisKey="IDPaciente", OtherKey="IDPaciente")]
		public EntitySet<Avaliacao> Avaliacaos
		{
			get
			{
				return this._Avaliacaos;
			}
			set
			{
				this._Avaliacaos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sessaos(Sessao entity)
		{
			this.SendPropertyChanging();
			entity.Paciente = this;
		}
		
		private void detach_Sessaos(Sessao entity)
		{
			this.SendPropertyChanging();
			entity.Paciente = null;
		}
		
		private void attach_Evolucaos(Evolucao entity)
		{
			this.SendPropertyChanging();
			entity.Paciente = this;
		}
		
		private void detach_Evolucaos(Evolucao entity)
		{
			this.SendPropertyChanging();
			entity.Paciente = null;
		}
		
		private void attach_Avaliacaos(Avaliacao entity)
		{
			this.SendPropertyChanging();
			entity.Paciente = this;
		}
		
		private void detach_Avaliacaos(Avaliacao entity)
		{
			this.SendPropertyChanging();
			entity.Paciente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Colaborador")]
	public partial class Colaborador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDColaborador;
		
		private string _Nome;
		
		private System.Nullable<System.DateTime> _DtNascimento;
		
		private string _Endereco;
		
		private string _RG;
		
		private string _CPF;
		
		private string _Email;
		
		private string _Telefone1;
		
		private string _Telefone2;
		
		private decimal _PorcComissao;
		
		private EntitySet<Sessao> _Sessaos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDColaboradorChanging(int value);
    partial void OnIDColaboradorChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnDtNascimentoChanging(System.Nullable<System.DateTime> value);
    partial void OnDtNascimentoChanged();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnRGChanging(string value);
    partial void OnRGChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelefone1Changing(string value);
    partial void OnTelefone1Changed();
    partial void OnTelefone2Changing(string value);
    partial void OnTelefone2Changed();
    partial void OnPorcComissaoChanging(decimal value);
    partial void OnPorcComissaoChanged();
    #endregion
		
		public Colaborador()
		{
			this._Sessaos = new EntitySet<Sessao>(new Action<Sessao>(this.attach_Sessaos), new Action<Sessao>(this.detach_Sessaos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDColaborador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDColaborador
		{
			get
			{
				return this._IDColaborador;
			}
			set
			{
				if ((this._IDColaborador != value))
				{
					this.OnIDColaboradorChanging(value);
					this.SendPropertyChanging();
					this._IDColaborador = value;
					this.SendPropertyChanged("IDColaborador");
					this.OnIDColaboradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DtNascimento", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DtNascimento
		{
			get
			{
				return this._DtNascimento;
			}
			set
			{
				if ((this._DtNascimento != value))
				{
					this.OnDtNascimentoChanging(value);
					this.SendPropertyChanging();
					this._DtNascimento = value;
					this.SendPropertyChanged("DtNascimento");
					this.OnDtNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="VarChar(100)")]
		public string Endereco
		{
			get
			{
				return this._Endereco;
			}
			set
			{
				if ((this._Endereco != value))
				{
					this.OnEnderecoChanging(value);
					this.SendPropertyChanging();
					this._Endereco = value;
					this.SendPropertyChanged("Endereco");
					this.OnEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RG
		{
			get
			{
				return this._RG;
			}
			set
			{
				if ((this._RG != value))
				{
					this.OnRGChanging(value);
					this.SendPropertyChanging();
					this._RG = value;
					this.SendPropertyChanged("RG");
					this.OnRGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(60)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone1", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Telefone1
		{
			get
			{
				return this._Telefone1;
			}
			set
			{
				if ((this._Telefone1 != value))
				{
					this.OnTelefone1Changing(value);
					this.SendPropertyChanging();
					this._Telefone1 = value;
					this.SendPropertyChanged("Telefone1");
					this.OnTelefone1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone2", DbType="VarChar(20)")]
		public string Telefone2
		{
			get
			{
				return this._Telefone2;
			}
			set
			{
				if ((this._Telefone2 != value))
				{
					this.OnTelefone2Changing(value);
					this.SendPropertyChanging();
					this._Telefone2 = value;
					this.SendPropertyChanged("Telefone2");
					this.OnTelefone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorcComissao", DbType="Decimal(5,2) NOT NULL")]
		public decimal PorcComissao
		{
			get
			{
				return this._PorcComissao;
			}
			set
			{
				if ((this._PorcComissao != value))
				{
					this.OnPorcComissaoChanging(value);
					this.SendPropertyChanging();
					this._PorcComissao = value;
					this.SendPropertyChanged("PorcComissao");
					this.OnPorcComissaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Colaborador_Sessao", Storage="_Sessaos", ThisKey="IDColaborador", OtherKey="IDColaborador")]
		public EntitySet<Sessao> Sessaos
		{
			get
			{
				return this._Sessaos;
			}
			set
			{
				this._Sessaos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sessaos(Sessao entity)
		{
			this.SendPropertyChanging();
			entity.Colaborador = this;
		}
		
		private void detach_Sessaos(Sessao entity)
		{
			this.SendPropertyChanging();
			entity.Colaborador = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HistSessaoPgto")]
	public partial class HistSessaoPgto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDHistSessaoPgto;
		
		private int _IDSessao;
		
		private decimal _PorcComissao;
		
		private EntityRef<Sessao> _Sessao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHistSessaoPgtoChanging(int value);
    partial void OnIDHistSessaoPgtoChanged();
    partial void OnIDSessaoChanging(int value);
    partial void OnIDSessaoChanged();
    partial void OnPorcComissaoChanging(decimal value);
    partial void OnPorcComissaoChanged();
    #endregion
		
		public HistSessaoPgto()
		{
			this._Sessao = default(EntityRef<Sessao>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHistSessaoPgto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDHistSessaoPgto
		{
			get
			{
				return this._IDHistSessaoPgto;
			}
			set
			{
				if ((this._IDHistSessaoPgto != value))
				{
					this.OnIDHistSessaoPgtoChanging(value);
					this.SendPropertyChanging();
					this._IDHistSessaoPgto = value;
					this.SendPropertyChanged("IDHistSessaoPgto");
					this.OnIDHistSessaoPgtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSessao", DbType="Int NOT NULL")]
		public int IDSessao
		{
			get
			{
				return this._IDSessao;
			}
			set
			{
				if ((this._IDSessao != value))
				{
					if (this._Sessao.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDSessaoChanging(value);
					this.SendPropertyChanging();
					this._IDSessao = value;
					this.SendPropertyChanged("IDSessao");
					this.OnIDSessaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorcComissao", DbType="Decimal(5,2) NOT NULL")]
		public decimal PorcComissao
		{
			get
			{
				return this._PorcComissao;
			}
			set
			{
				if ((this._PorcComissao != value))
				{
					this.OnPorcComissaoChanging(value);
					this.SendPropertyChanging();
					this._PorcComissao = value;
					this.SendPropertyChanged("PorcComissao");
					this.OnPorcComissaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sessao_HistSessaoPgto", Storage="_Sessao", ThisKey="IDSessao", OtherKey="IDSessao", IsForeignKey=true)]
		public Sessao Sessao
		{
			get
			{
				return this._Sessao.Entity;
			}
			set
			{
				Sessao previousValue = this._Sessao.Entity;
				if (((previousValue != value) 
							|| (this._Sessao.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sessao.Entity = null;
						previousValue.HistSessaoPgtos.Remove(this);
					}
					this._Sessao.Entity = value;
					if ((value != null))
					{
						value.HistSessaoPgtos.Add(this);
						this._IDSessao = value.IDSessao;
					}
					else
					{
						this._IDSessao = default(int);
					}
					this.SendPropertyChanged("Sessao");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sessao")]
	public partial class Sessao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDSessao;
		
		private int _IDPaciente;
		
		private int _IDColaborador;
		
		private decimal _Valor;
		
		private System.DateTime _DataSessao;
		
		private bool _Pago;
		
		private EntitySet<HistSessaoPgto> _HistSessaoPgtos;
		
		private EntityRef<Colaborador> _Colaborador;
		
		private EntityRef<Paciente> _Paciente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDSessaoChanging(int value);
    partial void OnIDSessaoChanged();
    partial void OnIDPacienteChanging(int value);
    partial void OnIDPacienteChanged();
    partial void OnIDColaboradorChanging(int value);
    partial void OnIDColaboradorChanged();
    partial void OnValorChanging(decimal value);
    partial void OnValorChanged();
    partial void OnDataSessaoChanging(System.DateTime value);
    partial void OnDataSessaoChanged();
    partial void OnPagoChanging(bool value);
    partial void OnPagoChanged();
    #endregion
		
		public Sessao()
		{
			this._HistSessaoPgtos = new EntitySet<HistSessaoPgto>(new Action<HistSessaoPgto>(this.attach_HistSessaoPgtos), new Action<HistSessaoPgto>(this.detach_HistSessaoPgtos));
			this._Colaborador = default(EntityRef<Colaborador>);
			this._Paciente = default(EntityRef<Paciente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSessao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDSessao
		{
			get
			{
				return this._IDSessao;
			}
			set
			{
				if ((this._IDSessao != value))
				{
					this.OnIDSessaoChanging(value);
					this.SendPropertyChanging();
					this._IDSessao = value;
					this.SendPropertyChanged("IDSessao");
					this.OnIDSessaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPaciente", DbType="Int NOT NULL")]
		public int IDPaciente
		{
			get
			{
				return this._IDPaciente;
			}
			set
			{
				if ((this._IDPaciente != value))
				{
					if (this._Paciente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPacienteChanging(value);
					this.SendPropertyChanging();
					this._IDPaciente = value;
					this.SendPropertyChanged("IDPaciente");
					this.OnIDPacienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDColaborador", DbType="Int NOT NULL")]
		public int IDColaborador
		{
			get
			{
				return this._IDColaborador;
			}
			set
			{
				if ((this._IDColaborador != value))
				{
					if (this._Colaborador.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDColaboradorChanging(value);
					this.SendPropertyChanging();
					this._IDColaborador = value;
					this.SendPropertyChanged("IDColaborador");
					this.OnIDColaboradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Decimal(5,2) NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataSessao", DbType="SmallDateTime NOT NULL")]
		public System.DateTime DataSessao
		{
			get
			{
				return this._DataSessao;
			}
			set
			{
				if ((this._DataSessao != value))
				{
					this.OnDataSessaoChanging(value);
					this.SendPropertyChanging();
					this._DataSessao = value;
					this.SendPropertyChanged("DataSessao");
					this.OnDataSessaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pago", DbType="Bit NOT NULL")]
		public bool Pago
		{
			get
			{
				return this._Pago;
			}
			set
			{
				if ((this._Pago != value))
				{
					this.OnPagoChanging(value);
					this.SendPropertyChanging();
					this._Pago = value;
					this.SendPropertyChanged("Pago");
					this.OnPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sessao_HistSessaoPgto", Storage="_HistSessaoPgtos", ThisKey="IDSessao", OtherKey="IDSessao")]
		public EntitySet<HistSessaoPgto> HistSessaoPgtos
		{
			get
			{
				return this._HistSessaoPgtos;
			}
			set
			{
				this._HistSessaoPgtos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Colaborador_Sessao", Storage="_Colaborador", ThisKey="IDColaborador", OtherKey="IDColaborador", IsForeignKey=true)]
		public Colaborador Colaborador
		{
			get
			{
				return this._Colaborador.Entity;
			}
			set
			{
				Colaborador previousValue = this._Colaborador.Entity;
				if (((previousValue != value) 
							|| (this._Colaborador.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Colaborador.Entity = null;
						previousValue.Sessaos.Remove(this);
					}
					this._Colaborador.Entity = value;
					if ((value != null))
					{
						value.Sessaos.Add(this);
						this._IDColaborador = value.IDColaborador;
					}
					else
					{
						this._IDColaborador = default(int);
					}
					this.SendPropertyChanged("Colaborador");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paciente_Sessao", Storage="_Paciente", ThisKey="IDPaciente", OtherKey="IDPaciente", IsForeignKey=true)]
		public Paciente Paciente
		{
			get
			{
				return this._Paciente.Entity;
			}
			set
			{
				Paciente previousValue = this._Paciente.Entity;
				if (((previousValue != value) 
							|| (this._Paciente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Paciente.Entity = null;
						previousValue.Sessaos.Remove(this);
					}
					this._Paciente.Entity = value;
					if ((value != null))
					{
						value.Sessaos.Add(this);
						this._IDPaciente = value.IDPaciente;
					}
					else
					{
						this._IDPaciente = default(int);
					}
					this.SendPropertyChanged("Paciente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HistSessaoPgtos(HistSessaoPgto entity)
		{
			this.SendPropertyChanging();
			entity.Sessao = this;
		}
		
		private void detach_HistSessaoPgtos(HistSessaoPgto entity)
		{
			this.SendPropertyChanging();
			entity.Sessao = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Evolucao")]
	public partial class Evolucao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDEvolucao;
		
		private System.DateTime _DataEvolucao;
		
		private string _Descricao;
		
		private int _IDPaciente;
		
		private EntityRef<Paciente> _Paciente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDEvolucaoChanging(int value);
    partial void OnIDEvolucaoChanged();
    partial void OnDataEvolucaoChanging(System.DateTime value);
    partial void OnDataEvolucaoChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnIDPacienteChanging(int value);
    partial void OnIDPacienteChanged();
    #endregion
		
		public Evolucao()
		{
			this._Paciente = default(EntityRef<Paciente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEvolucao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDEvolucao
		{
			get
			{
				return this._IDEvolucao;
			}
			set
			{
				if ((this._IDEvolucao != value))
				{
					this.OnIDEvolucaoChanging(value);
					this.SendPropertyChanging();
					this._IDEvolucao = value;
					this.SendPropertyChanged("IDEvolucao");
					this.OnIDEvolucaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataEvolucao", DbType="SmallDateTime NOT NULL")]
		public System.DateTime DataEvolucao
		{
			get
			{
				return this._DataEvolucao;
			}
			set
			{
				if ((this._DataEvolucao != value))
				{
					this.OnDataEvolucaoChanging(value);
					this.SendPropertyChanging();
					this._DataEvolucao = value;
					this.SendPropertyChanged("DataEvolucao");
					this.OnDataEvolucaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPaciente", DbType="Int NOT NULL")]
		public int IDPaciente
		{
			get
			{
				return this._IDPaciente;
			}
			set
			{
				if ((this._IDPaciente != value))
				{
					if (this._Paciente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPacienteChanging(value);
					this.SendPropertyChanging();
					this._IDPaciente = value;
					this.SendPropertyChanged("IDPaciente");
					this.OnIDPacienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paciente_Evolucao", Storage="_Paciente", ThisKey="IDPaciente", OtherKey="IDPaciente", IsForeignKey=true)]
		public Paciente Paciente
		{
			get
			{
				return this._Paciente.Entity;
			}
			set
			{
				Paciente previousValue = this._Paciente.Entity;
				if (((previousValue != value) 
							|| (this._Paciente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Paciente.Entity = null;
						previousValue.Evolucaos.Remove(this);
					}
					this._Paciente.Entity = value;
					if ((value != null))
					{
						value.Evolucaos.Add(this);
						this._IDPaciente = value.IDPaciente;
					}
					else
					{
						this._IDPaciente = default(int);
					}
					this.SendPropertyChanged("Paciente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Avaliacao")]
	public partial class Avaliacao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDAvaliacao;
		
		private System.DateTime _DataAvaliacao;
		
		private string _Descricao;
		
		private int _IDPaciente;
		
		private EntityRef<Paciente> _Paciente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDAvaliacaoChanging(int value);
    partial void OnIDAvaliacaoChanged();
    partial void OnDataAvaliacaoChanging(System.DateTime value);
    partial void OnDataAvaliacaoChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnIDPacienteChanging(int value);
    partial void OnIDPacienteChanged();
    #endregion
		
		public Avaliacao()
		{
			this._Paciente = default(EntityRef<Paciente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAvaliacao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDAvaliacao
		{
			get
			{
				return this._IDAvaliacao;
			}
			set
			{
				if ((this._IDAvaliacao != value))
				{
					this.OnIDAvaliacaoChanging(value);
					this.SendPropertyChanging();
					this._IDAvaliacao = value;
					this.SendPropertyChanged("IDAvaliacao");
					this.OnIDAvaliacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAvaliacao", DbType="SmallDateTime NOT NULL")]
		public System.DateTime DataAvaliacao
		{
			get
			{
				return this._DataAvaliacao;
			}
			set
			{
				if ((this._DataAvaliacao != value))
				{
					this.OnDataAvaliacaoChanging(value);
					this.SendPropertyChanging();
					this._DataAvaliacao = value;
					this.SendPropertyChanged("DataAvaliacao");
					this.OnDataAvaliacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPaciente", DbType="Int NOT NULL")]
		public int IDPaciente
		{
			get
			{
				return this._IDPaciente;
			}
			set
			{
				if ((this._IDPaciente != value))
				{
					if (this._Paciente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPacienteChanging(value);
					this.SendPropertyChanging();
					this._IDPaciente = value;
					this.SendPropertyChanged("IDPaciente");
					this.OnIDPacienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paciente_Avaliacao", Storage="_Paciente", ThisKey="IDPaciente", OtherKey="IDPaciente", IsForeignKey=true)]
		public Paciente Paciente
		{
			get
			{
				return this._Paciente.Entity;
			}
			set
			{
				Paciente previousValue = this._Paciente.Entity;
				if (((previousValue != value) 
							|| (this._Paciente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Paciente.Entity = null;
						previousValue.Avaliacaos.Remove(this);
					}
					this._Paciente.Entity = value;
					if ((value != null))
					{
						value.Avaliacaos.Add(this);
						this._IDPaciente = value.IDPaciente;
					}
					else
					{
						this._IDPaciente = default(int);
					}
					this.SendPropertyChanged("Paciente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwSessaoHistPgto")]
	public partial class vwSessaoHistPgto
	{
		
		private int _IDSessao;
		
		private int _IDColaborador;
		
		private int _IDPaciente;
		
		private System.DateTime _DataSessao;
		
		private decimal _Valor;
		
		private bool _Pago;
		
		private string _NomePaciente;
		
		private string _CPFPaciente;
		
		private decimal _PorcComissao;
		
		private string _NomeColaborador;
		
		private string _CPFColaborador;
		
		public vwSessaoHistPgto()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSessao", DbType="Int NOT NULL")]
		public int IDSessao
		{
			get
			{
				return this._IDSessao;
			}
			set
			{
				if ((this._IDSessao != value))
				{
					this._IDSessao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDColaborador", DbType="Int NOT NULL")]
		public int IDColaborador
		{
			get
			{
				return this._IDColaborador;
			}
			set
			{
				if ((this._IDColaborador != value))
				{
					this._IDColaborador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPaciente", DbType="Int NOT NULL")]
		public int IDPaciente
		{
			get
			{
				return this._IDPaciente;
			}
			set
			{
				if ((this._IDPaciente != value))
				{
					this._IDPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataSessao", DbType="SmallDateTime NOT NULL")]
		public System.DateTime DataSessao
		{
			get
			{
				return this._DataSessao;
			}
			set
			{
				if ((this._DataSessao != value))
				{
					this._DataSessao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Decimal(5,2) NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this._Valor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pago", DbType="Bit NOT NULL")]
		public bool Pago
		{
			get
			{
				return this._Pago;
			}
			set
			{
				if ((this._Pago != value))
				{
					this._Pago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomePaciente", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string NomePaciente
		{
			get
			{
				return this._NomePaciente;
			}
			set
			{
				if ((this._NomePaciente != value))
				{
					this._NomePaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPFPaciente", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CPFPaciente
		{
			get
			{
				return this._CPFPaciente;
			}
			set
			{
				if ((this._CPFPaciente != value))
				{
					this._CPFPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorcComissao", DbType="Decimal(5,2) NOT NULL")]
		public decimal PorcComissao
		{
			get
			{
				return this._PorcComissao;
			}
			set
			{
				if ((this._PorcComissao != value))
				{
					this._PorcComissao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeColaborador", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string NomeColaborador
		{
			get
			{
				return this._NomeColaborador;
			}
			set
			{
				if ((this._NomeColaborador != value))
				{
					this._NomeColaborador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPFColaborador", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CPFColaborador
		{
			get
			{
				return this._CPFColaborador;
			}
			set
			{
				if ((this._CPFColaborador != value))
				{
					this._CPFColaborador = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
